"""LMDB schema: key layout, serialization, lease encoding, and transaction helpers."""

from __future__ import annotations

from .codec import decode, encode
from .cursor import iter_prefix, parse_state_cursor
from .keys import (
    EMPTY,
    F64,
    JOB_TIMESTAMP_SIZE,
    META_STATS,
    META_TAIL,
    PFX_JOB,
    PFX_LEASE,
    PFX_LEASE_OFFSET,
    PFX_QUEUED,
    PFX_QUEUED_OFFSET,
    PFX_RETRY,
    PFX_STATE,
    PFX_STATE_OFFSET,
    U32,
    U64,
    key_job,
    key_lease,
    key_queued,
    key_retry,
    key_state,
)
from .lease import (
    CLAIM_TOKEN_LEN,
    lease_claim_token,
    lease_expiry,
    new_claim_token,
    new_lease,
    pack_lease,
)
from .schema import JobState, Stats
from .txn import (
    lease_is_expired_or_missing,
    meta_get,
    meta_set,
    requeue_running,
    retry_count,
    set_done,
    set_failed,
    set_pending,
    set_running,
    stats_get,
    stats_set,
)

__all__ = [
    "CLAIM_TOKEN_LEN",
    "EMPTY",
    "F64",
    "JOB_TIMESTAMP_SIZE",
    "META_STATS",
    "META_TAIL",
    "PFX_JOB",
    "PFX_LEASE",
    "PFX_LEASE_OFFSET",
    "PFX_QUEUED",
    "PFX_QUEUED_OFFSET",
    "PFX_RETRY",
    "PFX_STATE",
    "PFX_STATE_OFFSET",
    "U32",
    "U64",
    "JobState",
    "Stats",
    "decode",
    "encode",
    "iter_prefix",
    "key_job",
    "key_lease",
    "key_queued",
    "key_retry",
    "key_state",
    "lease_claim_token",
    "lease_expiry",
    "lease_is_expired_or_missing",
    "meta_get",
    "meta_set",
    "new_claim_token",
    "new_lease",
    "pack_lease",
    "parse_state_cursor",
    "requeue_running",
    "retry_count",
    "set_done",
    "set_failed",
    "set_pending",
    "set_running",
    "stats_get",
    "stats_set",
]
